### ISSUE TITLE
ImportError: No module named 'functions.RegNetModel.crop1_connection'

### ISSUE THREAD

**Issue by markemus** [hsokooti/RegNet#6]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/markemus/dev/RegNet/RegNet3D.py", line 17, in <module>
    import functions.RegNetModel as RegNetModel
  File "/home/markemus/dev/RegNet/functions/RegNetModel/__init__.py", line 17, in <module>
    from .crop1_connection import crop1_connection
ImportError: No module named 'functions.RegNetModel.crop1_connection'

```
I got this error trying to run RegNet3D.py. Commenting those imports fixed the error, and grep doesn't show any usage for them.

**Comment by hsokooti** [comment]
Dear markemus, 

Thank you for your feedback. That bug is now fixed.
